behaviors:
  MoveToGoal:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 124000
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
      buffer_init_steps: 0
      init_entcoef: 0.6
      tau: 5.0e-3
      steps_per_update: 1
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        max_steps: 2000000
        time_horizon: 64
        summary_freq: 10000
            